# Generated by Django 3.0.6 on 2021-02-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_num', models.IntegerField(default=0)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('greek_org', models.CharField(max_length=20)),
                ('class_year', models.IntegerField(default=0)),
                ('housing_building', models.CharField(max_length=20)),
                ('housing_num', models.CharField(max_length=20)),
                ('club', models.CharField(max_length=20)),
                ('sport', models.CharField(max_length=20)),
                ('current_class', models.CharField(max_length=20)),
            ],
        ),
    ]
