# Generated by Django 3.0.6 on 2021-04-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_modifed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
