# Generated by Django 3.0.6 on 2021-04-12 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_student_last_modifed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
