# Generated by Django 3.0.6 on 2021-04-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_delete_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
