# Generated by Django 3.0.6 on 2021-04-14 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_delete_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='housing_num',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='sport',
            new_name='gender',
        ),
    ]
